[package]
name = "keeplisten"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29"
crossterm = "0.29"
lazy_static = "1"
nix = { version = "0.30", features = ["signal", "process"] }
libc = "0.2"
